
################### English Navigation ########################
[[main]]
name = "About"
url = "#about"
weight = 1

# [[main]]
# name = "services"
# url = "#services"
# weight = 2

[[main]]
name = "Science"
url = "#our-science"
weight = 2

[[main]]
name = "Team"
url = "#team"
weight = 3

# [[main]]
# name = "pricing"
# url = "#pricing"
# weight = 5

# [[main]]
# name = "Profiles"
# url = "#testimonial"
# weight = 3.5

[[main]]
name = "Advisory Board"
url = "#advisory"
weight = 4

[[main]]
name = "Collaborators"
url = "#collaborators"
weight = 5

[[main]]
name = "news"
url = "#blog"
weight = 6

[[main]]
name = "contact"
url = "#contact"
weight = 7


############## Example how to create a dropdown menu
# [[main]]
# name = "Dropdown"
# weight = 6
# hasChildren = true
# 
# [[main]]
# parent = "Dropdown"
# name = "Dropdown 1"
# url = "#"
# weight = 1
# 
# [[main]]
# parent = "Dropdown"
# name = "Dropdown 2"
# url = "#"
# weight = 2



############## Example linking to other sites
# [[main]]
# name = "themefisher"
# url = "https://themefisher.com/"
# weight = 8

